In [2]:
##
"""
Comparison between explicit for loop and vectorization
"""

import numpy as np

a = np.random.rand(1000000)
b = np.random.rand(1000000)

import time

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print("Vectorization : " + str(1000 * (toc-tic)) + "ms")


tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()

print("Non vectorization : " + str(1000 * (toc-tic)) + "ms")

Vectorization : 131.000041962ms
Non vectorization : 613.000154495ms


In [3]:
## Broadcasting examples

A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])

print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [4]:
cal = A.sum(axis=0)
print(cal)

[  59.   239.   155.4   76.9]


In [6]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [11]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
c.shape

(12288L, 45L)